In [6]:
import duckdb

df = duckdb.sql("SELECT * FROM 'station_metadata.parquet' LIMIT 10").df()
df

  station_id               name       lon        lat   alt
0        abo    Adelboden (ABO)  7.560703  46.491703  <NA>
1        aeg    Oberägeri (AEG)  8.608206  47.133636  <NA>
2        aig        Aigle (AIG)  6.924472  46.326647  <NA>
3        alt      Altdorf (ALT)  8.621894  46.887069  <NA>
4        and       Andeer (AND)  9.431981  46.610139  <NA>
5        ant    Andermatt (ANT)  8.580553  46.630914  <NA>
6        arh   Altenrhein (ARH)  9.566850  47.483631  <NA>
7        aro        Arosa (ARO)  9.679014  46.792661  <NA>
8        att  Les Attelas (ATT)  7.268650  46.099100  <NA>
9        ban     Bantiger (BAN)  7.528667  46.977806  <NA>

In [9]:
df = duckdb.sql("SELECT * FROM 'dataset_with_weather.parquet' LIMIT 1000").df()
df

,timestamp,time_sin,time_cos,dow_sin,dow_cos,month_sin,month_cos,is_weekend,operator,line,...,departure_delay_s,temperature,precipitation,sunshine,humidity,wind_speed,wind_gust,wind_dir,pressure,snow_depth
0,2025-01-01 11:18:00,0.000000,1.000000,0.974928,-0.222521,0.5,0.866025,False,sbg034,Bus33,...,120,4.4,0.0,3600.0,55.0,11.4,24.799999,239.0,980.200012,0.0
1,2025-01-01 11:20:00,0.173648,-0.984808,0.974928,-0.222521,0.5,0.866025,False,sbg034,Bus33,...,60,4.4,0.0,3600.0,55.0,11.4,24.799999,239.0,980.200012,0.0
2,2025-01-01 11:22:00,0.165048,-0.986286,0.974928,-0.222521,0.5,0.866025,False,sbg034,Bus33,...,120,4.4,0.0,3600.0,55.0,11.4,24.799999,239.0,980.200012,0.0
3,2025-01-01 11:23:00,0.160743,-0.986996,0.974928,-0.222521,0.5,0.866025,False,sbg034,Bus33,...,120,4.4,0.0,3600.0,55.0,11.4,24.799999,239.0,980.200012,0.0
4,2025-01-01 11:25:00,0.152123,-0.988362,0.974928,-0.222521,0.5,0.866025,False,sbg034,Bus33,...,180,4.4,0.0,3600.0,55.0,11.4,24.799999,239.0,980.200012,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2025-01-01 12:25:00,-0.108867,-0.994056,0.974928,-0.222521,0.5,0.866025,False,BOS/rtb,252,...,21,6.4,0.0,3600.0,42.0,3.6,12.200000,150.0,979.099976,0.0
996,2025-01-01 12:26:00,-0.113203,-0.993572,0.974928,-0.222521,0.5,0.866025,False,BOS/rtb,252,...,-5,6.4,0.0,3600.0,42.0,3.6,12.200000,150.0,979.099976,0.0
997,2025-01-01 12:28:00,-0.121869,-0.992546,0.974928,-0.222521,0.5,0.866025,False,BOS/rtb,252,...,55,6.4,0.0,3600.0,42.0,3.6,12.200000,150.0,979.099976,0.0
998,2025-01-01 12:32:00,-0.139173,-0.990268,0.974928,-0.222521,0.5,0.866025,False,BOS/rtb,252,...,-17,6.4,0.0,3600.0,42.0,3.6,12.200000,150.0,979.099976,0.0
999,2025-01-01 12:33:00,-0.143493,-0.989651,0.974928,-0.222521,0.5,0.866025,False,BOS/rtb,252,...,44,6.4,0.0,3600.0,42.0,3.6,12.200000,150.0,979.099976,0.0

In [13]:
df = duckdb.sql("SELECT * FROM 'weather_hourly.parquet' LIMIT 400").df()
df

,station_id,timestamp,temperature,precipitation,sunshine,humidity,wind_speed,wind_gust,wind_dir,pressure,snow_depth
0,abo,2025-01-01 00:00:00,-5.7,0.0,0.0,55.0,7.6,29.200001,187.0,868.700012,70.0
1,abo,2025-01-01 01:00:00,-6.8,0.0,0.0,61.0,7.8,31.000000,185.0,868.000000,70.0
2,abo,2025-01-01 02:00:00,-6.8,0.0,0.0,60.0,6.7,29.900000,186.0,868.299988,70.0
3,abo,2025-01-01 03:00:00,-6.0,0.0,0.0,57.0,5.8,27.000000,187.0,868.700012,70.0
4,abo,2025-01-01 04:00:00,-5.9,0.0,0.0,56.0,7.1,28.799999,187.0,868.500000,70.0
...,...,...,...,...,...,...,...,...,...,...,...
395,abo,2025-01-17 11:00:00,3.7,0.0,3600.0,44.0,0.4,6.500000,360.0,877.200012,124.0
396,abo,2025-01-17 12:00:00,3.4,0.0,3600.0,47.0,2.4,9.400000,9.0,876.500000,124.0
397,abo,2025-01-17 13:00:00,2.8,0.0,3600.0,53.0,2.8,12.600000,15.0,876.400024,123.0
398,abo,2025-01-17 14:00:00,2.7,0.0,3600.0,57.0,1.0,10.100000,329.0,876.200012,123.0
399,abo,2025-01-17 15:00:00,1.6,0.0,3600.0,57.0,0.4,4.700000,333.0,875.299988,123.0