In [2]:
import duckdb

df = duckdb.sql("SELECT * FROM 'station_metadata.parquet' LIMIT 10").df()
df

  station_id               name       lon        lat   alt
0        abo    Adelboden (ABO)  7.560703  46.491703  <NA>
1        aeg    Oberägeri (AEG)  8.608206  47.133636  <NA>
2        aig        Aigle (AIG)  6.924472  46.326647  <NA>
3        alt      Altdorf (ALT)  8.621894  46.887069  <NA>
4        and       Andeer (AND)  9.431981  46.610139  <NA>
5        ant    Andermatt (ANT)  8.580553  46.630914  <NA>
6        arh   Altenrhein (ARH)  9.566850  47.483631  <NA>
7        aro        Arosa (ARO)  9.679014  46.792661  <NA>
8        att  Les Attelas (ATT)  7.268650  46.099100  <NA>
9        ban     Bantiger (BAN)  7.528667  46.977806  <NA>

In [17]:
df = duckdb.sql("SELECT * FROM 'dataset_with_weather.parquet' LIMIT 1000").df()
df

,timestamp,time_sin,time_cos,dow_sin,dow_cos,month_sin,month_cos,is_weekend,operator,line,...,temperature,precipitation,sunshine,humidity,wind_speed,wind_gust,wind_dir,pressure,snow_depth,is_public_holiday
0,2025-01-04 05:17:00,0.982450,0.186524,-0.974928,-0.222521,0.5,0.866025,True,sbg034,Bus33,...,-4.8,0.0,0.0,100.0,0.194444,0.694444,104.0,975.700012,0.00,False
1,2025-01-04 05:19:00,0.984041,0.177944,-0.974928,-0.222521,0.5,0.866025,True,sbg034,Bus33,...,-4.8,0.0,0.0,100.0,0.194444,0.694444,104.0,975.700012,0.00,False
2,2025-01-04 20:18:00,0.000000,1.000000,-0.974928,-0.222521,0.5,0.866025,True,sbg034,Bus33,...,-1.3,0.1,0.0,83.0,0.527778,1.888889,107.0,968.700012,0.00,False
3,2025-01-04 20:20:00,-0.819152,0.573576,-0.974928,-0.222521,0.5,0.866025,True,sbg034,Bus33,...,-1.3,0.1,0.0,83.0,0.527778,1.888889,107.0,968.700012,0.00,False
4,2025-01-04 20:22:00,-0.814116,0.580703,-0.974928,-0.222521,0.5,0.866025,True,sbg034,Bus33,...,-1.3,0.1,0.0,83.0,0.527778,1.888889,107.0,968.700012,0.00,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2025-01-04 10:11:00,0.457874,-0.889017,-0.974928,-0.222521,0.5,0.866025,True,BOS/rtb,252,...,-3.2,0.0,1.0,54.0,1.333333,4.500000,193.0,973.599976,0.03,False
996,2025-01-04 10:12:00,0.453990,-0.891007,-0.974928,-0.222521,0.5,0.866025,True,BOS/rtb,252,...,-3.2,0.0,1.0,54.0,1.333333,4.500000,193.0,973.599976,0.03,False
997,2025-01-04 10:15:00,0.000000,1.000000,-0.974928,-0.222521,0.5,0.866025,True,BOS/rtb,252,...,-5.0,0.0,1.0,57.0,0.416667,2.611111,187.0,927.700012,0.13,False
998,2025-01-04 10:16:00,0.438371,-0.898794,-0.974928,-0.222521,0.5,0.866025,True,BOS/rtb,252,...,-3.2,0.0,1.0,54.0,1.333333,4.500000,193.0,973.599976,0.03,False
999,2025-01-04 10:17:00,0.434445,-0.900698,-0.974928,-0.222521,0.5,0.866025,True,BOS/rtb,252,...,-3.2,0.0,1.0,54.0,1.333333,4.500000,193.0,973.599976,0.03,False

In [15]:
df = duckdb.sql("SELECT * FROM 'dataset_with_weather.parquet' WHERE snow_depth IS NOT NULL ORDER BY snow_depth DESC LIMIT 20").df()
df

,timestamp,time_sin,time_cos,dow_sin,dow_cos,month_sin,month_cos,is_weekend,operator,line,...,departure_delay_s,temperature,precipitation,sunshine,humidity,wind_speed,wind_gust,wind_dir,pressure,snow_depth
0,2025-01-04 05:27:00,0.989651,1.434926e-01,-0.974928,-0.222521,0.5,0.866025,True,MGB/Autofo,142,...,107,-14.2,0.0,0.0,21.0,1.416667,6.805556,276.0,707.000000,33.330002
1,2025-01-04 05:28:00,0.990268,1.391731e-01,-0.974928,-0.222521,0.5,0.866025,True,MGB/Autofo,142,...,95,-14.2,0.0,0.0,21.0,1.416667,6.805556,276.0,707.000000,33.330002
2,2025-01-04 05:28:00,0.990268,1.391731e-01,-0.974928,-0.222521,0.5,0.866025,True,MGB/Autofo,142,...,<NA>,-14.2,0.0,0.0,21.0,1.416667,6.805556,276.0,707.000000,33.330002
3,2025-01-04 05:28:00,0.990268,1.391731e-01,-0.974928,-0.222521,0.5,0.866025,True,MGB/Autofo,142,...,<NA>,-14.2,0.0,0.0,21.0,1.416667,6.805556,276.0,707.000000,33.330002
4,2025-01-04 05:29:00,0.990866,1.348509e-01,-0.974928,-0.222521,0.5,0.866025,True,MGB/Autofo,142,...,116,-14.2,0.0,0.0,21.0,1.416667,6.805556,276.0,707.000000,33.330002
5,2025-01-04 05:30:00,0.991445,1.305262e-01,-0.974928,-0.222521,0.5,0.866025,True,MGB/Autofo,142,...,130,-14.2,0.0,0.0,21.0,1.416667,6.805556,276.0,707.000000,33.330002
6,2025-01-04 05:31:00,0.992005,1.261990e-01,-0.974928,-0.222521,0.5,0.866025,True,MGB/Autofo,142,...,<NA>,-14.2,0.0,0.0,21.0,1.416667,6.805556,276.0,707.000000,33.330002
7,2025-01-04 05:34:00,0.993572,1.132032e-01,-0.974928,-0.222521,0.5,0.866025,True,MGB/Autofo,142,...,193,-14.2,0.0,0.0,21.0,1.416667,6.805556,276.0,707.000000,33.330002
8,2025-01-04 05:37:00,0.994969,1.001881e-01,-0.974928,-0.222521,0.5,0.866025,True,MGB/Autofo,142,...,267,-14.2,0.0,0.0,21.0,1.416667,6.805556,276.0,707.000000,33.330002
9,2025-01-04 05:43:00,0.997250,7.410849e-02,-0.974928,-0.222521,0.5,0.866025,True,MGB/Autofo,142,...,<NA>,-14.2,0.0,0.0,21.0,1.416667,6.805556,276.0,707.000000,33.330002
10,2025-01-04 05:45:00,0.997859,6.540313e-02,-0.974928,-0.222521,0.5,0.866025,True,MGB/Autofo,142,...,321,-14.2,0.0,0.0,21.0,1.416667,6.805556,276.0,707.000000,33.330002
11,2025-01-04 05:46:00,0.998135,6.104854e-02,-0.974928,-0.222521,0.5,0.866025,True,MGB/Autofo,142,...,296,-14.2,0.0,0.0,21.0,1.416667,6.805556,276.0,707.000000,33.330002
12,2025-01-04 05:49:00,0.998848,4.797813e-02,-0.974928,-0.222521,0.5,0.866025,True,MGB/Autofo,142,...,<NA>,-14.2,0.0,0.0,21.0,1.416667,6.805556,276.0,707.000000,33.330002
13,2025-01-04 05:50:00,0.000000,1.000000e+00,-0.974928,-0.222521,0.5,0.866025,True,MGB/Autofo,142,...,35,-14.2,0.0,0.0,21.0,1.416667,6.805556,276.0,707.000000,33.330002
14,2025-01-04 05:50:00,0.999048,4.361939e-02,-0.974928,-0.222521,0.5,0.866025,True,MGB/Autofo,142,...,114,-14.2,0.0,0.0,21.0,1.416667,6.805556,276.0,707.000000,33.330002
15,2025-01-04 05:51:00,0.999229,3.925982e-02,-0.974928,-0.222521,0.5,0.866025,True,MGB/Autofo,142,...,79,-14.2,0.0,0.0,21.0,1.416667,6.805556,276.0,707.000000,33.330002
16,2025-01-04 05:53:00,0.999534,3.053851e-02,-0.974928,-0.222521,0.5,0.866025,True,MGB/Autofo,142,...,<NA>,-14.2,0.0,0.0,21.0,1.416667,6.805556,276.0,707.000000,33.330002
17,2025-01-04 06:00:00,1.000000,6.123234e-17,-0.974928,-0.222521,0.5,0.866025,True,MGB/Autofo,142,...,135,-13.7,0.0,0.0,19.0,1.361111,6.388889,270.0,707.200012,33.330002
18,2025-01-04 06:03:00,0.999914,-1.308960e-02,-0.974928,-0.222521,0.5,0.866025,True,MGB/Autofo,142,...,<NA>,-13.7,0.0,0.0,19.0,1.361111,6.388889,270.0,707.200012,33.330002
19,2025-01-04 06:08:00,0.999391,-3.489950e-02,-0.974928,-0.222521,0.5,0.866025,True,MGB/Autofo,142,...,<NA>,-13.7,0.0,0.0,19.0,1.361111,6.388889,270.0,707.200012,33.330002

In [16]:
df.iloc[0]

timestamp              2025-01-04 05:27:00
time_sin                          0.989651
time_cos                          0.143493
dow_sin                          -0.974928
dow_cos                          -0.222521
month_sin                              0.5
month_cos                         0.866025
is_weekend                            True
operator                        MGB/Autofo
line                                   142
stop_id                            8578566
stop_name            Naters, Tünnelstrasse
additional_trip                      False
arrival_delay_s                        100
departure_delay_s                      107
temperature                          -14.2
precipitation                          0.0
sunshine                               0.0
humidity                              21.0
wind_speed                        1.416667
wind_gust                         6.805556
wind_dir                             276.0
pressure                             707.0
snow_depth                       33.330002
Name: 0, dtype: object

In [25]:
df = duckdb.sql("SELECT * FROM 'dataset_with_weather.parquet' WHERE is_public_holiday = TRUE LIMIT 100").df()
df

,timestamp,time_sin,time_cos,dow_sin,dow_cos,month_sin,month_cos,is_weekend,operator,line,...,temperature,precipitation,sunshine,humidity,wind_speed,wind_gust,wind_dir,pressure,snow_depth,is_public_holiday
0,2025-01-01 11:56:00,0.017452,-0.999848,0.974928,-0.222521,0.5,0.866025,False,RVBW,5,...,7.4,0.0,1.0,44.0,2.194444,5.500000,215.0,986.200012,0.0,True
1,2025-01-01 12:03:00,0.000000,1.000000,0.974928,-0.222521,0.5,0.866025,False,RVBW,5,...,9.1,0.0,1.0,36.0,2.472222,5.888889,218.0,985.099976,0.0,True
2,2025-01-01 12:04:00,-0.017452,-0.999848,0.974928,-0.222521,0.5,0.866025,False,RVBW,5,...,9.1,0.0,1.0,36.0,2.472222,5.888889,218.0,985.099976,0.0,True
3,2025-01-01 12:05:00,-0.021815,-0.999762,0.974928,-0.222521,0.5,0.866025,False,RVBW,5,...,9.1,0.0,1.0,36.0,2.472222,5.888889,218.0,985.099976,0.0,True
4,2025-01-01 12:07:00,-0.030539,-0.999534,0.974928,-0.222521,0.5,0.866025,False,RVBW,5,...,9.1,0.0,1.0,36.0,2.472222,5.888889,218.0,985.099976,0.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2025-01-01 14:12:00,-0.544639,-0.838671,0.974928,-0.222521,0.5,0.866025,False,RVBW,5,...,5.3,0.0,1.0,39.0,3.555556,8.694445,230.0,926.500000,0.0,True
96,2025-01-01 14:14:00,-0.551937,-0.833886,0.974928,-0.222521,0.5,0.866025,False,RVBW,5,...,5.3,0.0,1.0,39.0,3.555556,8.694445,230.0,926.500000,0.0,True
97,2025-01-01 14:17:00,-0.562805,-0.826590,0.974928,-0.222521,0.5,0.866025,False,RVBW,5,...,5.3,0.0,1.0,39.0,3.555556,8.694445,230.0,926.500000,0.0,True
98,2025-01-01 14:17:00,-0.562805,-0.826590,0.974928,-0.222521,0.5,0.866025,False,RVBW,5,...,5.3,0.0,1.0,39.0,3.555556,8.694445,230.0,926.500000,0.0,True
99,2025-01-01 14:17:00,-0.562805,-0.826590,0.974928,-0.222521,0.5,0.866025,False,RVBW,5,...,5.3,0.0,1.0,39.0,3.555556,8.694445,230.0,926.500000,0.0,True